apiVersion: apps/v1
kind: Deployment
metadata:
  name: take-home-shift-deployment
spec:
  selector:
    matchLabels:
      run: users-app
  template:
    metadata:
      labels:
        run: users-app
    spec:
      containers:
      - name: users-app
        image: watchbleo/users-app:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: take-home-shift-deployment
  labels:
    run: users-app
spec:
  ports:
  - port: 5000
  selector:
    run: users-app

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: take-home-shift-deployment
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: take-home-shift-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

## Use this block for networking latency

# type: Object
# object:
#   metric:
#     name: requests-per-second
#   describedObject:
#     apiVersion: networking.k8s.io/v1
#     kind: Ingress
#     name: main-route
#   target:
#     type: Value
#     value: 2k 


